### ISSUE TITLE
Macro doesn't find the bibliography created by Mendeley

### ISSUE THREAD

**Issue by PanagiotisIliop** [mabentwickeltsich/MendeleyMacros#16] opened 2022-10-16 19:07 UTC
This code doesn't work for the latest versions of Mendeley.

An error message is presnted :"the bibliography could not be located in the document. make sure that you have inserted the bibliography via the Mendeley's plugin and that the custom configuration of the GAUG_* macros is correct. Cannot continue removing hyperlinks." 

Any ideas on how to update the code to work for the latest versions of Mendeley?

**Comment by mabentwickeltsich** [comment] 2022-10-21 08:28
Dear @PanagiotisIliop,

I have not being able to test the macros with the new version of Mendelay. It is probably this line that should be changed:
`If sectionField.Type = wdFieldAddin And Trim(sectionField.Code) = "ADDIN Mendeley Bibliography CSL_BIBLIOGRAPHY" Then`
I assume the name of the ADDIN has changed with the new version of Mendelay.

The easiest way would be to use an older version of Mendelay to avoid the issue as I am not sure when I would be able to correct the code.

Cheers

**Comment by PanagiotisIliop** [comment] 2022-10-28 15:05
Thanks for the reply,
Best wishes!!!

**Comment by chadouhoney** [comment] 2023-10-28 16:43
@PanagiotisIliop did you manage to overcome the issue? If yes, how?

**Comment by ChrisVeigl** [comment] 2024-09-26 10:00
Hi,  
I tried to change the field code in

`If sectionField.Type = wdFieldAddin And Trim(sectionField.Code) = "ADDIN Mendeley Bibliography CSL_BIBLIOGRAPHY" Then`

withough success - it seems that the loop

` For Each sectionField In documentSection.range.Fields`
 
is not even entered ... maybe something in the document structure changed in newer versions of Word?

**Comment by mabentwickeltsich** [comment] 2024-11-20 17:26
Dear @PanagiotisIliop, @chadouhoney and @ChrisVeigl,

the issue is related to the new version of Mendeley which has changed the way the citations and bibliography are inserted into the document. The new release of Mendeley Macros has new features and a fix for this problem.

Cheers

**Closed as completed by mabentwickeltsich** 2024-11-20 17:26 UTC
