### ISSUE TITLE
Macro doesn't find the bibliography created by Mendeley

### ISSUE THREAD

**Issue by amirghd10** [mabentwickeltsich/MendeleyMacros#14] opened 2022-05-19 08:19 UTC
Hi dear Tony
I'm using the latest version of Mendeley (v2.71.0) and when I'm running the Marco, I get the error of "The Bibliography could not be located in the document. Make sure that you have inserted the bibliography via the Mendeley's plugin"; which I did!
I did no modification to the citations so the styles are the same and I worked with both IEEE and APA citation styles and the error didn't change.
I think the error is due to the new update of Mendeley which split it completely from word citation tab and your macro needs to be updated to figure out the change.
Thanks a lot
![image](https://user-images.githubusercontent.com/36996457/169246686-db58e1e6-1de2-43b9-bf46-ccdd3057c0b2.png)

**Comment by mabentwickeltsich** [comment] 2022-10-21 08:48
Dear @amirghd10,

thank you very much for the feedback. I have not been able to work with the macros since long time ago. I am sorry to find out that the new version of Mendeley uses a different approach to add the citations and bibliography. My suggestion is to use an older version of Mendeley to avoid the issue as I cannot tell when I would be able to have a look at the problem.
By the way, I am not Tony 😉

Cheers

**Comment by mabentwickeltsich** [comment] 2024-11-20 17:27
Dear @amirghd10,

the issue is related to the new version of Mendeley which has changed the way the citations and bibliography are inserted into the document. The new release of Mendeley Macros has new features and a fix for this problem.

Cheers

**Closed as completed by mabentwickeltsich** 2024-11-20 17:27 UTC
