### ISSUE TITLE
Lots of references & other issues

### ISSUE THREAD

**Issue by Azaxa242** [mabentwickeltsich/MendeleyMacros#6] opened 2019-01-14 16:10 UTC
Hi there,

First off, great macro idea!

Few issues though.

1) I have 200+ references and when I execute the code it says "Orphan citation entry found: [###] Remove it from document!". I think this is due to the line "Name:="SignetBibliographie_" & Format(CStr(intRefereceNumber), "00#"), _" whereby it only accepts one digit references.

![image](https://user-images.githubusercontent.com/46682393/51124673-c382ff00-1816-11e9-9012-8b76d3da438a.png)

2) When executing the code for one digit references the original reference [1] turns into [**SignetBibliographie_001**1] where bold is the new hyperlink and non-bold is the original text that hasn't been deleted.

![image](https://user-images.githubusercontent.com/46682393/51124695-d269b180-1816-11e9-87dc-68ccedcabc4f.png)

Any assistance on this would be great and would complete the macro for me!

Thanks,
Steven

**Comment by mabentwickeltsich** [comment] 2019-01-14 16:59
Dear Steven,

I introduced the orphan citation check when I found that one particular citation was not being linked in a document of another user. The number of citations and references should not be a problem; also my document has more than 200 of them and around 300 pages of length.

According to the information you provided, it seems that citation [67] is the problem. I do not think it has to do with the number of digits, as you suggested; otherwise the error would appear much earlier. I suggest you to check that the citation was inserted by the Mendeley plugin (not directly by Microsoft Word) and that it has a corresponding reference in the bibliography (also inserted by the Mendeley plugin).

In addition, would it be possible for you to send me one document that produces the error? It may be easier to perform tests here and find what the problem is. Finally, are you using the latest commit?

Kind regards
Luis

**Comment by Azaxa242** [comment] 2019-01-14 17:14
Hi Luis,

I have the Aug 2017 commit.

This doesn't just happen for [67] but for all references above [10]. 

Do you have an email I can send this to?

Thanks,
Steven

**Comment by mabentwickeltsich** [comment] 2019-01-14 17:31
Dear Steven,

then I really need to have a look at the document you are using. My emial address is:
jose-luis.gonzalez-garcia -at- gwdg.de

Kind regards
Luis

**Comment by Azaxa242** [comment] 2019-01-14 17:37
Hi Luis,

I have sent the document.

Please contact me either on here or via email when you can.

Thanks,
Steven

**Comment by Azaxa242** [comment] 2019-01-14 20:48
If this occurs use the following code. If this changes the format of other things like picture format and justification then simply go into Word -> File -> Info -> Compatibility Mode (at the top) -> Convert. Code courtesy of Luis:

1. Sub GAUG_createHyperlinksForCitationsIEEE()
Set the flag to True and comment the part with the style:

```
        blnFound = True
'        blnFound = False
'        With documentSection.Range.Find
'            .Style = "Titre de dernière section"
'            .Execute
'            blnFound = .Found
'        End With
```


2. Sub GAUG_createHyperlinksForCitationsAPA()
Set the flag to True and comment the part with the style:

```
        blnFound = True
'        blnFound = False
'        With documentSection.Range.Find
'            .Style = "Titre de dernière section"
'            .Execute
'            blnFound = .Found
'        End With
```


3. Sub GAUG_removeHyperlinksForCitations(Optional ByVal strTypeOfExecution As String = "RemoveHyperlinks")
Same here, set the flag and comment the code:

```
        blnFound = True
'        blnFound = False
'        With documentSection.Range.Find
'            .Style = "Titre de dernière section"
'            .Execute
'            blnFound = .Found
'        End With

```

**Comment by mabentwickeltsich** [comment] 2019-01-15 16:47
Dear Steven,

that is what I did to run the macros with your document (as stated in [Extending/modifying the code](https://github.com/mabentwickeltsich/MendeleyMacros/blob/master/README.md#extendingmodifying-the-code)) because you do not have the style "Titre de dernière section" and your bibliography is not in a section with the title using that style.

I did not have any problem at all; the macros run smoothly with your document.

Regards
Luis

**Comment by mabentwickeltsich** [comment] 2019-04-01 15:57
Closing the issue as the new code DOES NOT require any modification in order to be used.

**Closed as completed by mabentwickeltsich** 2019-04-01 15:57 UTC
